# Generated by Django 4.1.3 on 2023-05-29 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateTimeField(verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='relevance',
            field=models.CharField(choices=[('HI', 'High'), ('MD', 'Medium'), ('LOW', 'Low')], default='MD', max_length=12, verbose_name='Relevance'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='urgency',
            field=models.CharField(choices=[('HI', 'High'), ('MD', 'Medium'), ('LOW', 'Low')], default='MD', max_length=12, verbose_name='Urgency'),
        ),
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.BooleanField(verbose_name='Done?'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Task name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent_goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.goal', verbose_name='Linked Goal'),
        ),
    ]
