# Generated by Django 4.1.3 on 2022-11-21 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daily',
            options={'verbose_name_plural': 'Daily habit'},
        ),
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['-created']},
        ),
    ]
