# Generated by Django 4.1.3 on 2022-11-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_alter_daily_options_alter_habit_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
